### ISSUE TITLE
Mostrar tareas recientemente pausadas o pendientes.

### ISSUE THREAD

**Issue by lesthack** [EdgarVaguencia/khaleesiApp#1]
Estaría padre que en la extensión, si no tienes tareas activas te muestre las últimas tareas en las que estuviste trabajando. Estas son las que recientemente marcaste como pausadas o pendientes. Así, ya no tendrías que ir al khaleesi para volver a encender una tarea.

El json/board ahora ya cuenta con esta información.
https://github.com/lesthack/khaleesi/commit/ea784b5a961608f2288898d5972bdede04ca9d24

:+1:

**Comment by EdgarVaguencia** [comment]
En la versión 0.2.0 :facepunch: de chrome se agregan estas tareas, con la posibilidad de iniciar alguna, independiente si tienes activas o no.
